import * as stylex from "@stylexjs/stylex";
import { ReactNode } from "react";

export const metadata = {
  title: "StyleX by WebDev Simplified",
  description: "Generated by create next app",
};

const styles = stylex.create({
  html: {
    colorScheme: "light dark",
  },
  reset: {
    minHeight: "100%",
    margin: 0,
    padding: 0,
  },
  body: {
    backgroundImage: {
      default: "linear-gradient(to bottom, rgb(214, 219, 220), white)",
    },
  },
});

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html {...stylex.props(styles.html, styles.reset)} lang="en">
      <body {...stylex.props(styles.reset, styles.body)}>{children}</body>
    </html>
  );
}
